# Data dtstribution is a list of all possible values, and how often each values occurs...
# such lists are important when working with statics and data science....
import random

# Random Distribution...
# A Random distribution is a set of random numbers that follows a certain probability density function...
# choice() method of random module...
#from numpy import random...

import numpy as n
x = n.random.choice([3,5,6,7], p = [0.1,0.2,0.3,0.4], size = (100))
print(x)

#A permutation refers to an arrangement of elemts...
# [3,2,1] is permutation of [1,2,3]
# suffle(), permutation ()

arr = n.array([1,2,3,4,5])
n.random.shuffle(arr)
print(arr)

print(n.random.permutation(arr))
